//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accountant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accountant()
        {
            this.MoneyTransferStatus = new HashSet<MoneyTransferStatus>();
        }
    
        public int Acc_id { get; set; }
        public string Acc_name { get; set; }
        public string Acc_lastname { get; set; }
        public string Acc_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoneyTransferStatus> MoneyTransferStatus { get; set; }
    }
}
