//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR
    {
        public int HR_id { get; set; }
        public string HR_name { get; set; }
        public string HR_lastname { get; set; }
        public string HR_username { get; set; }
        public string HR_password { get; set; }
        public string HR_phone { get; set; }
    }
}
