//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightEmp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RightEmp()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int rig_no { get; set; }
        public string rig_name { get; set; }
        public Nullable<decimal> rig_balance { get; set; }
        public string rig_Uname { get; set; }
        public Nullable<System.DateTime> rig_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
